[package]
name = "glacier2obj"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
categories = ["game-development", "data-structures", "parser-implementations"]
description = "Get ALOCs from a Glacier scene."
repository = "https://github.com/dbierek/glacier2obj"
readme = "README.md"

[badges.maintenance]
status = "actively-developed"

[dependencies]
rpkg-rs = "=1.0.0-rc.1"
binrw = "0.13.3"
modular-bitfield = "0.11.2"
memmap2 = "0.9.4"
lazy-regex = "3.1.0"
lz4 = "1.24.0"
pathdiff = "0.2.1"
itertools = { version = "0.12.1", features = [] }
thiserror = "1.0.59"
md-5 = "0.10.6"
extended-tea = "0.1.1"
byteorder = "1.5.0"
rayon = { version = "1.10.0", optional = true}
serde = { version = "1.0.199", optional = true, features = ["derive"] }
serde-hex = { version = "0.1.0", optional = true }
tungstenite = { version = "0.16.0", features = ["native-tls"]}
url = "2.2.2"

[features]
default = ["path-list", "serde"]
path-list = ["dep:rayon"]
serde = ["dep:serde", "dep:serde-hex"]

[dev-dependencies]
serde_json = "1.0.116"
version-sync = "0.9.5"
